### ISSUE TITLE
Request: Update for new AWS dashboard (both Lamba and Skills section)

### ISSUE THREAD

**Issue by favna** [dblock/alexa-parrot#1]
Title pretty much says it all. The dashboard has changed a lot since the creation of this tutorial and this tutorial is a great way for beginners to start as you explain it in a very good way in the video. While I understand it may be too much asked to make an updated video, it would be nice to edit the readme to reflect the new dashboard.

**Comment by dblock** [comment]
Appreciate a PR! Give it a try.

**Comment by favna** [comment]
Sure will do. I'm currently going through the tutorial still so once I got it all figured out I'll look into that.
