### ISSUE TITLE
[CI-Guide] Travis

### ISSUE THREAD

**Issue by favna** [dblock/alexa-parrot#3]
As per your request, making an issue out of the further requirements.

I've set up config files for CircleCI and TravisCI. The former [is fully working](https://circleci.com/gh/dblock/alexa-parrot/2). For Travis, please add this repo to building on their platform.

Lastly a question, I see you're in the jenkinsci organization so I have a feeling you want Jenkins to be among the CI Options as well? I've never used it myself but I suppose I can figure out its format for config file if so.

That all said, once that passes and is done I'll create a PR from the CI-Guide branch to master.

**Comment by dblock** [comment]
I only part of the jenkins org because I wrote https://github.com/jenkinsci/ansicolor-plugin, I haven't used Jenkins in 5 years ;) Circle, Travis, all good with me. 

You can make a PR, I enabled Circle-CI

If you prefer Travis I can do that, I don't have any strong opinions. Pick one.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/alexa-parrot/pull/4
